baseURL = "https://tamhn.netlify.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Tam's Personal Blog"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-139233829-1"
disqusShortname = "tam17995"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "“You cannot do a kindness too soon, for you never know how soon it will be too late.” Ralph Waldo Emerson"
  dateFormat = "2019-04-11"
  codePenUser = "tamhn"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    url = "/project/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "Bài tiếng việt"
    url = "/vietnamese/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
